### ISSUE TITLE
csv格式问题

### ISSUE THREAD

**Issue by JuggGO** [spytensor/image_aug_for_detection#1]
您好，我根据您的指示，制作的CSV文件之后运行出现
PermissionError: [Errno 13] Permission denied: './data/augmented/csv_files/augmented_labels.csv'
我的csvcsv文件格式如下图
![image](https://user-images.githubusercontent.com/48093072/57312996-3e9f5680-7121-11e9-8db1-5c158957631f.png)
请问是否是csv文件的问题导致这个错误？

**Comment by tinothy22** [comment]
Did you solve this problem? I had the same problem.

**Comment by Charcy-yang** [comment]
您好，请问您在转化过程有调整代码吗，我在报错了，您可以帮忙看下吗？谢谢您了
`D:\Python\python.exe C:/Users/Administrator/Desktop/coco_aug/example.py 0%| | 0/2 [00:00<?, ?it/s] Traceback (most recent call last): File "C:/Users/Administrator/Desktop/coco_aug/example.py", line 109, in <module> detection_augumentor.fit() File "C:/Users/Administrator/Desktop/coco_aug/example.py", line 35, in fit image = Image.open(image_path) # D:\Python\Lib\site-packages\PIL\Image.py File "D:\Python\lib\site-packages\PIL\Image.py", line 2618, in open prefix = fp.read(16) UnicodeDecodeError: 'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence`
